# Generated by Django 6.0.3 on 2026-04-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscribe_to_blog',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscribe_to_forum',
            field=models.BooleanField(default=False),
        ),
    ]
